# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Artco' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Artco
pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'FirebaseUI/Google'
pod 'Firebase/Storage'
pod 'Cloudinary', '~> 2.0'
pod 'DropDown'
pod 'AlamofireImage', '~> 3.5'

  target 'ArtcoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArtcoUITests' do
    # Pods for testing
  end

end
